"""Send the daily briefing as a styled HTML email via Gmail SMTP."""
import html as _html
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv

load_dotenv()

# Inline-styled HTML email. Email clients (Gmail, Outlook) strip <style> blocks
# and external CSS, so every style lives inline on the element itself.
_WRAPPER = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#eef1f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#eef1f5;padding:24px 12px;">
    <tr><td align="center">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:14px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
        <!-- Header -->
        <tr><td style="background:linear-gradient(135deg,#4f46e5 0%,#7c3aed 100%);padding:32px 32px 28px;">
          <div style="color:#ffffff;font-size:13px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;opacity:0.85;">Daily Briefing</div>
          <div style="color:#ffffff;font-size:26px;font-weight:700;margin-top:6px;">{weekday}</div>
          <div style="color:#e0e7ff;font-size:15px;margin-top:2px;">{long_date}</div>
        </td></tr>
        <!-- Body -->
        <tr><td style="padding:28px 32px 8px;color:#1f2937;font-size:15px;line-height:1.6;">
{content}
        </td></tr>
        <!-- Footer -->
        <tr><td style="padding:20px 32px 28px;border-top:1px solid #eef1f5;color:#9ca3af;font-size:12px;line-height:1.5;">
          Auto-generated by your Daily Briefing assistant · {long_date}<br>
          Covering Gmail, Outlook &amp; Hotmail inboxes, calendar, and Google News.
        </td></tr>
      </table>
      <div style="color:#b6bcc6;font-size:11px;margin-top:16px;">Sent securely via Gmail · read-only inbox access</div>
    </td></tr>
  </table>
</body>
</html>"""


def _md_to_html(markdown_text: str) -> str:
    """Convert briefing markdown to styled inline HTML fragments."""
    try:
        import markdown as md
        raw = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    except ImportError:
        return "<pre style='white-space:pre-wrap;'>" + _html.escape(markdown_text) + "</pre>"

    # Inline-style the generated tags so they survive email clients.
    replacements = {
        "<h1>": '<h1 style="font-size:22px;font-weight:700;color:#111827;margin:0 0 16px;">',
        "<h2>": '<h2 style="font-size:17px;font-weight:700;color:#4f46e5;margin:26px 0 10px;padding-bottom:6px;border-bottom:2px solid #eef1f5;">',
        "<h3>": '<h3 style="font-size:14px;font-weight:700;color:#6b7280;margin:16px 0 6px;text-transform:uppercase;letter-spacing:0.5px;">',
        "<ul>": '<ul style="margin:6px 0 14px;padding-left:20px;">',
        "<li>": '<li style="margin:4px 0;color:#374151;">',
        "<p>": '<p style="margin:8px 0;color:#374151;">',
        "<strong>": '<strong style="color:#111827;font-weight:600;">',
        "<em>": '<em style="color:#6b7280;font-style:normal;">',
        "<code>": '<code style="background:#f3f4f6;color:#4f46e5;padding:1px 6px;border-radius:4px;font-size:12px;">',
    }
    for old, new in replacements.items():
        raw = raw.replace(old, new)
    return raw


def send_briefing(markdown_text: str, date_str: str) -> None:
    smtp_user = os.environ.get("GMAIL_SMTP_USER", "")
    smtp_password = os.environ.get("GMAIL_SMTP_PASSWORD", "")
    to_email = os.environ.get("BRIEFING_TO_EMAIL", smtp_user)

    if not smtp_user or not smtp_password:
        print("[skip] GMAIL_SMTP_USER / GMAIL_SMTP_PASSWORD not set — skipping email")
        return

    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        weekday, long_date = dt.strftime("%A"), dt.strftime("%B %d, %Y")
    except ValueError:
        weekday, long_date = "Today", date_str

    html_body = _WRAPPER.format(
        weekday=weekday, long_date=long_date, content=_md_to_html(markdown_text)
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"☀️ Daily Briefing — {weekday}, {long_date}"
    msg["From"] = f"Daily Briefing <{smtp_user}>"
    msg["To"] = to_email
    msg.attach(MIMEText(markdown_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(smtp_user, smtp_password)
        smtp.sendmail(smtp_user, [to_email], msg.as_string())

    print(f"✓ Email sent to {to_email}")
