import base64
import re
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from googleapiclient.discovery import build
from .google_auth import get_creds


def _md_to_html(text: str) -> str:
    """Convert the subset of markdown Claude uses in briefings to HTML."""
    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        # Section header: **Title**
        if re.match(r"^\*\*[^*]+\*\*$", line.strip()):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            heading = re.sub(r"\*\*(.+?)\*\*", r"\1", line.strip())
            html_lines.append(f'<h3 style="color:#1a1a2e;margin-top:24px;margin-bottom:8px;">{heading}</h3>')
        # Bullet / numbered list item
        elif re.match(r"^[-\d][\.\s]", line.strip()):
            if not in_list:
                html_lines.append('<ul style="padding-left:20px;margin:4px 0;">')
                in_list = True
            item = re.sub(r"^[-\d]+[.\s]+", "", line.strip())
            item = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", item)
            html_lines.append(f"<li style='margin:4px 0;'>{item}</li>")
        # Empty line
        elif line.strip() == "":
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<br>")
        # Normal paragraph
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            para = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            html_lines.append(f"<p style='margin:4px 0;'>{para}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def send_briefing(briefing_text: str, to: str) -> None:
    creds = get_creds()
    service = build("gmail", "v1", credentials=creds)

    today = datetime.now().strftime("%A, %B %d, %Y")
    subject = f"Daily Briefing — {today}"

    html_body = f"""<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
             max-width:680px;margin:0 auto;padding:24px;color:#222;line-height:1.6;">
  <h2 style="color:#1a1a2e;border-bottom:2px solid #eee;padding-bottom:12px;">
    Daily Briefing &mdash; {today}
  </h2>
  {_md_to_html(briefing_text)}
  <p style="margin-top:32px;color:#aaa;font-size:11px;border-top:1px solid #eee;padding-top:12px;">
    Generated by Daily Briefing &middot; Powered by Claude
  </p>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = "me"
    msg["To"] = to
    msg.attach(MIMEText(briefing_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    service.users().messages().send(userId="me", body={"raw": raw}).execute()
    print(f"Emailed to {to}")
